[platformio]
extra_configs = private_config.ini

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ===== BUILD FLAGS =====
build_flags =
    ; Blynk Credentials (from private_config.ini)
    -D MY_BLYNK_TEMPLATE_ID=\"${secret_credentials.BLYNK_TEMPLATE_ID}\"
    -D MY_BLYNK_TEMPLATE_NAME=\"${secret_credentials.BLYNK_TEMPLATE_NAME}\"
    -D MY_BLYNK_AUTH_TOKEN=\"${secret_credentials.BLYNK_AUTH_TOKEN}\"
    
    ; W5500 Configuration
    -D W5500_CS_PIN=5
    -D W5500_RST_PIN=4
    -D W5500_INT_PIN=34
    
    ; Pin Configuration
    -D ESP_LED_PIN=13
    -D RESET_WIFI_PIN=15
    
    ; I2C Configuration
    -D MCP_RL1_ADDR=0x20
    -D MCP_SW1_ADDR=0x21
    
    ; RTC Configuration
    -D RTC_TYPE_DS3231=1

; ===== LIBRARIES =====
lib_deps =
    https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library.git
    https://github.com/blynkkk/blynk-library.git
    https://github.com/adafruit/RTClib.git
    https://github.com/PaulStoffregen/Time
    https://github.com/Blynk-Technologies/blynk-library.git
    https://github.com/tzapu/WiFiManager.git
    https://github.com/arduino-libraries/Ethernet.git

; ===== BUILD OPTIONS =====
build_unflags =
    -Os
build_type = release
