[platformio]
extra_configs = private_config.ini

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library.git
    https://github.com/blynkkk/blynk-library.git
    https://github.com/adafruit/RTClib.git
    https://github.com/PaulStoffregen/Time
    https://github.com/Blynk-Technologies/blynk-library.git
    https://github.com/tzapu/WiFiManager.git

build_flags =
    -D MY_BLYNK_TEMPLATE_ID=\"${secret_credentials.BLYNK_TEMPLATE_ID}\"
    -D MY_BLYNK_TEMPLATE_NAME=\"${secret_credentials.BLYNK_TEMPLATE_NAME}\"
    -D MY_BLYNK_AUTH_TOKEN=\"${secret_credentials.BLYNK_AUTH_TOKEN}\"